import { promises as fs } from "node:fs";
import path from "node:path";

const rootDir = process.cwd();
const contentDir = path.join(rootDir, "content");
const generatedDir = path.join(rootDir, "generated");
const profileFile = "profile-main.md";
const uiFile = "config-ui.md";
const aiFile = "config-ai.md";
const generatedSiteFile = "generated-site.md";
const generatedIndexFile = "generated-content-index.md";
const generatedAiContextFile = "ai-context.json";
const generatedClaudeSkillFile = "claude-code-skill.md";
const generatedLlmsFile = "llms.txt";

async function main() {
  const files = await fs.readdir(contentDir);
  const markdownFiles = files.filter((file) => file.endsWith(".md"));

  if (!markdownFiles.includes(profileFile) || !markdownFiles.includes(uiFile) || !markdownFiles.includes(aiFile)) {
    throw new Error("content/profile-main.md, content/config-ui.md, and content/config-ai.md are required.");
  }

  const managedFiles = markdownFiles.filter(
    (file) => file !== generatedSiteFile && file !== generatedIndexFile
  );

  const blogFiles = managedFiles.filter((file) => /^post-.*\.md$/i.test(file)).sort();
  const projectFiles = managedFiles.filter((file) => /^project-.*\.md$/i.test(file)).sort();
  const raceFiles = managedFiles.filter((file) => /^race-.*\.md$/i.test(file)).sort();
  const skillFiles = managedFiles.filter((file) => /^skill-.*\.md$/i.test(file)).sort();

  const profileRaw = await fs.readFile(path.join(contentDir, profileFile), "utf8");
  const { attributes: profile, body: profileBody } = parseFrontmatter(profileRaw);
  const uiRaw = await fs.readFile(path.join(contentDir, uiFile), "utf8");
  const { attributes: ui } = parseFrontmatter(uiRaw);
  const aiRaw = await fs.readFile(path.join(contentDir, aiFile), "utf8");
  const { attributes: ai } = parseFrontmatter(aiRaw);
  const siteTitle = profile.name || "Markdown Portfolio";
  const posts = await loadTypedEntries(blogFiles);
  const projects = await loadTypedEntries(projectFiles);
  const races = await loadTypedEntries(raceFiles);
  const skills = await loadTypedEntries(skillFiles);
  const sortedBlogFiles = [...posts]
    .sort((a, b) => new Date(b.date || 0) - new Date(a.date || 0))
    .map((entry) => entry.file);

  const navLabels = Object.fromEntries(
    parseArrayPairs(ui.nav_labels).map((item) => [item.key, item.value])
  );
  const nav = [];
  if (navLabels.about) nav.push(`"${escapeQuotes(navLabels.about)}|#about-panel"`);
  if (blogFiles.length && navLabels.posts) nav.push(`"${escapeQuotes(navLabels.posts)}|#featured-post"`);
  if (projectFiles.length && navLabels.projects) nav.push(`"${escapeQuotes(navLabels.projects)}|#projects-panel"`);
  if (skillFiles.length && navLabels.skills) nav.push(`"${escapeQuotes(navLabels.skills)}|#skills-panel"`);
  if (raceFiles.length && navLabels.races) nav.push(`"${escapeQuotes(navLabels.races)}|#races-panel"`);

  const siteContents = [
    "---",
    "type: site",
    `title: "${escapeQuotes(siteTitle)}"`,
    `nav: [${nav.join(", ")}]`,
    "---",
    "",
    "This file is auto-generated by scripts/sync-content.mjs.",
    "",
  ].join("\n");

  const indexEntries = [
    generatedSiteFile,
    profileFile,
    uiFile,
    aiFile,
    ...sortedBlogFiles,
    ...projectFiles,
    ...skillFiles,
    ...raceFiles,
  ];
  const indexContents = `${indexEntries.map((file) => `- ${file}`).join("\n")}\n`;

  const aiContext = buildAiContext({
    ai,
    profile,
    profileBody,
    posts,
    projects,
    skills,
    races,
  });
  const claudeCodeSkill = buildClaudeCodeSkill(aiContext, ai);
  const llms = buildLlms(aiContext, ai);

  await fs.mkdir(generatedDir, { recursive: true });
  await fs.writeFile(path.join(contentDir, generatedSiteFile), siteContents, "utf8");
  await fs.writeFile(path.join(contentDir, generatedIndexFile), indexContents, "utf8");
  await fs.writeFile(
    path.join(generatedDir, generatedAiContextFile),
    `${JSON.stringify(aiContext, null, 2)}\n`,
    "utf8"
  );
  await fs.writeFile(path.join(generatedDir, generatedClaudeSkillFile), claudeCodeSkill, "utf8");
  await fs.writeFile(path.join(rootDir, generatedLlmsFile), llms, "utf8");

  console.log(`Updated ${generatedSiteFile} and ${generatedIndexFile}.`);
  console.log(
    `Found ${blogFiles.length} post file(s), ${projectFiles.length} project file(s), ${skillFiles.length} skill file(s), and ${raceFiles.length} race file(s).`
  );
}

async function loadTypedEntries(files) {
  const entries = [];
  for (const file of files) {
    const raw = await fs.readFile(path.join(contentDir, file), "utf8");
    const parsed = parseFrontmatter(raw);
    entries.push({
      file,
      ...parsed.attributes,
      body: parsed.body,
    });
  }
  return entries;
}

function parseFrontmatter(raw) {
  const normalized = raw.replace(/\r\n/g, "\n");
  if (!normalized.startsWith("---\n")) {
    return { attributes: {}, body: normalized.trim() };
  }

  const endIndex = normalized.indexOf("\n---\n", 4);
  if (endIndex === -1) {
    return { attributes: {}, body: normalized.trim() };
  }

  const frontmatter = normalized.slice(4, endIndex).trim();
  const body = normalized.slice(endIndex + 5).trim();
  const attributes = {};

  for (const line of frontmatter.split("\n")) {
    const separator = line.indexOf(":");
    if (separator === -1) continue;
    const key = line.slice(0, separator).trim();
    const value = line.slice(separator + 1).trim();
    attributes[key] = parseFrontmatterValue(value);
  }

  return { attributes, body };
}

function parseFrontmatterValue(value) {
  if (!value) return "";
  if (value.startsWith("[") && value.endsWith("]")) {
    return value
      .slice(1, -1)
      .split(",")
      .map((item) => item.trim())
      .filter(Boolean)
      .map((item) => item.replace(/^"(.*)"$/, "$1").replace(/^'(.*)'$/, "$1"));
  }

  return value.replace(/^"(.*)"$/, "$1").replace(/^'(.*)'$/, "$1");
}

function escapeQuotes(value) {
  return String(value).replace(/"/g, '\\"');
}

function parseArrayPairs(items) {
  return (Array.isArray(items) ? items : []).map((item) => {
    const [key, ...rest] = String(item).split("|");
    return { key: key.trim(), value: rest.join("|").trim() };
  });
}

function stripMarkdown(markdown) {
  return markdown
    .replace(/^#+\s+/gm, "")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, "$1")
    .replace(/^- /gm, "")
    .trim();
}

function buildAiContext({ ai, profile, profileBody, posts, projects, skills, races }) {
  const sortedPosts = [...posts].sort((a, b) => new Date(b.date || 0) - new Date(a.date || 0));
  const sortedProjects = [...projects].sort(
    (a, b) => new Date(b.updated || b.date || 0) - new Date(a.updated || a.date || 0)
  );
  const sortedSkills = [...skills].sort((a, b) => new Date(b.updated || 0) - new Date(a.updated || 0));

  return {
    site: {
      title: profile.name || "Markdown Portfolio",
      person: profile.name || "",
      googleAnalyticsId: profile.ga_measurement_id || "",
      generatedAt: new Date().toISOString(),
    },
    ai: {
      panelTitle: ai.panel_title || "",
      panelIntro: ai.panel_intro || "",
      panelLinks: Array.isArray(ai.panel_links) ? ai.panel_links : [],
    },
    profile: {
      name: profile.name || "",
      tagline: profile.tagline || "",
      topics: Array.isArray(profile.topics) ? profile.topics : [],
      links: Array.isArray(profile.links) ? profile.links : [],
      bio: stripMarkdown(profileBody),
    },
    recentBlogs: sortedPosts.slice(0, 8).map(toAiEntry),
    pastProjects: sortedProjects.slice(0, 12).map(toAiEntry),
    claudeCodeSkills: sortedSkills.slice(0, 12).map(toAiEntry),
    races: races.map(toAiEntry),
  };
}

function toAiEntry(entry) {
  return {
    title: entry.title || "",
    summary: entry.summary || "",
    date: entry.date || "",
    updated: entry.updated || "",
    status: entry.status || "",
    category: entry.category || "",
    tags: Array.isArray(entry.tags) ? entry.tags : [],
    repo: entry.repo || "",
    docs: entry.docs || "",
    file: entry.file,
    content: stripMarkdown(entry.body || ""),
  };
}

function buildClaudeCodeSkill(aiContext, ai) {
  const recentBlogLines = aiContext.recentBlogs
    .map((post) => `- ${post.title}${post.date ? ` (${post.date})` : ""}: ${post.summary}`)
    .join("\n");
  const projectLines = aiContext.pastProjects
    .map((project) => `- ${project.title}: ${project.summary}`)
    .join("\n");
  const skillLines = aiContext.claudeCodeSkills
    .map((skill) => `- ${skill.title}: ${skill.summary}`)
    .join("\n");

  return [
    `# ${aiContext.site.person || aiContext.site.title} ${ai.skill_title_suffix || ""}`.trim(),
    "",
    ai.skill_purpose || "",
    "",
    `## ${ai.skill_instruction_heading || ""}`,
    "",
    ...(Array.isArray(ai.skill_instructions) ? ai.skill_instructions.map((item) => `- ${item}`) : []),
    "",
    `## ${ai.skill_profile_heading || ""}`,
    "",
    aiContext.profile.bio || "No bio provided.",
    "",
    `## ${ai.skill_recent_blogs_heading || ""}`,
    "",
    recentBlogLines || `- ${ai.skill_empty_blogs || ""}`,
    "",
    `## ${ai.skill_past_projects_heading || ""}`,
    "",
    projectLines || `- ${ai.skill_empty_projects || ""}`,
    "",
    `## ${ai.skill_skills_heading || ""}`,
    "",
    skillLines || `- ${ai.skill_empty_skills || ""}`,
    "",
  ].join("\n");
}

function buildLlms(aiContext, ai) {
  const descriptions = Object.fromEntries(parseArrayPairs(ai.llms_resource_descriptions).map((item) => [item.key, item.value]));
  const links = parseArrayPairs(aiContext.ai.panelLinks).map((item) => {
    const description = descriptions[item.key] || "";
    return `- [${item.key}](${item.value}): ${description}`;
  });
  const introTemplate = ai.llms_intro_template || "";
  const intro = introTemplate.replace("{name}", aiContext.profile.name || "the site owner");

  return [
    "# " + (aiContext.site.title || "Markdown Portfolio"),
    "",
    intro,
    "",
    aiContext.profile.bio || "",
    "",
    `## ${ai.llms_resources_heading || ""}`,
    "",
    ...links,
    "",
  ].join("\n");
}

main().catch((error) => {
  console.error(error.message);
  process.exitCode = 1;
});
